#@ load("@ytt:data", "data")

---
profile: light
ceip_policy_disclosed: true

buildservice:
  kp_default_repository: #@ "index.docker.io/{}/build-service".format(data.values.docker_username)
  kp_default_repository_username: #@ data.values.docker_username
  kp_default_repository_password: #@ data.values.docker_password
  tanzunet_username: #@ data.values.tanzunet_username
  tanzunet_password: #@ data.values.tanzunet_password
  enable_automatic_dependency_updates: false

supply_chain: basic

cnrs:
  provider: local
  domain_name: minikube

ootb_supply_chain_basic:
  registry:
    server: index.docker.io
    repository: #@ data.values.docker_username
  gitops:
    ssh_secret: ""

tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: "minikube"
  app_config:
    app:
      baseUrl: http://tap-gui.minikube
    catalog:
      locations:
        - type: url
          target: https://github.com/ccheetham/sandbox/blob/tap-gui-catalog/catalog-info.yaml
    backend:
      baseUrl: http://tap-gui.minikube
      cors:
        origin: http://tap-gui.minikube

metadata_store:
  app_service_type: NodePort
