:toc:
:toclevels: 3
:toc-placement!:
:toc-title!:
:linkattrs:

= _Tanzu Thingies_ =

toc::[]

== Overview

This repo contains a collection of utilities to help with things Tanzu.

|===
| Util | Description

| `minikube-delete` | Deletes a Minikube cluster.
| `minikube-start` | Creates/starts a Minikube cluster.
| `minikube-stop` | Stops a Minikube cluster cluster.
| `minikube-tunnel` | Creates a Minikube cluster tunnel.
| `tap-install` | Installs TAP into current K8s context.
| `tap-profile` | Creates a TAP profile.
| `tap-version` | Displays the version of TAP running in the current K8s context.
|===

Many of the example commands below work as-is on both Windows and non-Windows and can be copy-pasted as is.

.Sample Command
----
$ bin/sample-command
----

In situations where this is not the case, platform-specific commands are shown.

.Sample Platform Commands
----
# OSX
$ bin/osx-command

# Windows
> bin\win-command.ps1
----

== Prereqs

=== Docker for Desktop

https://www.docker.com/products/docker-desktop/

If using a WSL backend, check out https://docs.microsoft.com/en-us/windows/wsl/wsl-config#wslconfig[instructions for increasing resource allocation].

=== `envsubst`

.envsubst
----
# OSX
$ homebrew install gettext

# Windows
> scoop install envsubst
----

=== `jq`

----
# OSX
$ homebrew install jq

# Windows
> scoop install jq
----

=== `minikube`

----
# OSX
$ brew install minikube

# Windows
> scoop install minikube
----

=== `unzip`

`unzip` is only required for Windows.

----
# Windows
> scoop install unzip
----

== Configure

Configuration is set by loading the `config` for your platform.

The utilities in this repo load configuration when they are run.

You can load the configuration into your shell by sourcing `etc/config`.

NOTE: Shell examples in this doc assume a loaded configuration.

.Shell Configuration
----
$ . etc/config
----

=== Settings

The default settings should work out-of-the-box.

Default settings are defined in:

* `link:etc/config[]`
* `link:etc/tap[]`
* `link:etc/minikube[]`

To override defaults, copy `link:share/examples/overrides[]` to `etc/`.

.Overrides
----
# OSX/Linux
$ cp share/examples/overrides etc/

# Windows
$ copy share\examples\overrides.ps1 etc\
----

.Sample `etc/overrides`
----
MINIKUBE_MEMORY=6g
TAP_VERSION=1.2.2
----

=== Credentials

Credentials are defined in a specialized configuration that is ignored by Git.

Copy `link:share/examples/credentials[]` to `etc/`.

.Credentials
----
# OSX/Linux
$ cp share/examples/credentials etc/

# Windows
$ copy share\examples\credentials.ps1 etc\
----

Configure credentials for TanzuNet and a Docker registry.

.Sample `etc/credentials`
----
REGISTRY_HOST=harbor-repo.vmware.com
REGISTRY_USER=joe
REGISTRY_PASS=joepass
REGISTRY_REPO=joes_tap

TANZUNET_USER=joe@company.com
TANZUNET_PASS=joepassdeux
----

== TAP Tools

=== Tanzu CLI

Go to the the TanzuNet downloads for https://network.tanzu.vmware.com/products/tanzu-application-platform/[VMware Tanzu Application Platform, window="_new"].

Select the release that matches `TAP_VERSION`.

Select the `tap-cli-tap` bundle for your platform and download.

Move/rename the downloaded file into `LOCAL_DIST_DIR`.

.Example
----
# OSX
$ mkdir -p $DIST_DIR
$ mv ~/Downloads/tanzu-framework-darwin-amd64.tar ${LOCAL_DIST_DIR}/tanzu-framework-darwin-amd64-${TAP_VERSION}.tar

# Windows
$ mkdir $Env:LOCAL_DIR
$ mkdir $Env:LOCAL_DIST_DIR
$ move "$Env:UserProfile\Downloads\tanzu-framework-windows-amd64.zip" "$Env:LOCAL_DIST_DIR\tanzu-framework-windows-amd64-$Env:TAP_VERSION.zip"
----

=== Tanzu Cluster Essentials

NOTE: This step is not required on Windows.

Go to the the TanzuNet downloads for https://network.tanzu.vmware.com/products/tanzu-cluster-essentials[Cluster Essentials for VMware Tanzu, window="_new"].

Select the release that matches `TANZU_ESSENTIALS_VERSION`.

Move the downloaded file into `LOCAL_DIST_DIR`.

.Example
----
# OSX
$ mkdir -p $DIST_DIR
$ mv ~/Downloads/tanzu-cluster-essentials-darwin-amd64-$TANZU_ESSENTIALS_VERSION.tar ${LOCAL_DIST_DIR}/
----

== Cluster

=== Minikube Cluster

Running `minikube-start` creates a cluster if necessary and then starts it.

----
$ bin/minikube-start
----

=== Minikube Tunnel

NOTE: The Minikube tunnel may require elevated permissions.

The tunnel is required for TAP installation.
If packages are failing to reconcile, it may be due to lack of a running tunnel.

The tunnel runs in the foreground, `CTRL-C` to kill.

----
$ bin/minikube-tunnel
----

== TAP

=== Before You Begin

See above for details on following checklist:

* ensure cluster is running
* ensure cluster tunnel is running
* TAP product bundles are downloaded into expected paths
* corporate VPN running

=== TAP Profile

Generate a TAP Profile based on your settings.
You only need to do this once, or when you've changed settings.

----
$ bin/tap-profile
----

=== TAP Install

Install TAP into the current K8s context.

----
$ bin/tap-install
----

=== Workload Notes

Deployed apps will be assigned an HTTP route of the form:

`http://NAME.default.example.com`

where `NAME` is that specified in the command:

`tanzu apps workload create NAME ...`.

You must add a matching entry to your local hosts resolving the route host to the loopback IF.

Host file locations:

|===
| Platform | path

| OSX | `/etc/hosts`
| Windows |  `C:\Windows\System32\drivers\etc\hosts`
|===

.Sample
----
127.0.0.1	NAME.default.example.com
----

