:toc:
:toclevels: 3
:toc-placement!:
:toc-title!:
:linkattrs:

= _Tanzu Thingies_ =

toc::[]

== Prerequisites

=== PowerShell

For Windows, install a recent version, >=7.2, from the the PowerShell https://github.com/PowerShell/PowerShell/releases[releases].
The PowerShell that ships with Windows is too old for these scripts.

For OS X, install using: `brew install powershell`

=== Docker for Desktop

Install https://www.docker.com/products/docker-desktop/[Docker Desktop] for your platform

If using a WSL backend and Minikube is complaining about not enough resources, check out https://docs.microsoft.com/en-us/windows/wsl/wsl-config#wslconfig[instructions for increasing WSL resource allocation].

=== 3rd Party Tools

The prerequisite 3rd party tools for your platform are defined in one of:

* `link:etc/prereqs-darwin.ps1[]`
* `link:etc/prereqs-windows.ps1[]`

You can install the tools manually, or by running:

----
PS> bin/prereq-install.ps1
----
Running the above script requires one of the below installers:

|===
| Installer | Platform | Home

| `brew` | OS X | https://brew.sh/
| `scoop` | Windows | https://scoop.sh/
|===

=== Tanzu Tools

The Tanzu CLI and Cluster Essentials are required.
You only need to download the distributions; the tools will be installed as needed for you.

Below are a scripted approach (using the `pivnet` CLI) and a manual approach to download the distributions.

=== Scripted Using pivnet CLI

Install `pivnet` from the https://github.com/pivotal-cf/pivnet-cli/[Pivnet CLI] project, either using a platform installer or downloading a release.

Ensure the file is executable and on your path. On Windows be sure to rename the file to `pivnet.exe`.

After the CLI is installed, https://network.pivotal.io/docs/api#how-to-authenticate[login, window="_new"] to the https://network.pivotal.io/[Tanzu Network, window="_new"].

Once logged in, fetch the distributions by running:

----
PS> bin/tanzu-fetch.ps1
----

=== Manual Downloads

==== Tanzu CLI

Go to the the TanzuNet downloads for https://network.tanzu.vmware.com/products/tanzu-application-platform/[VMware Tanzu Application Platform, window="_new"].

Select the release that matches `$TapVersion`.

Select the `tanzu-cli-tap` distribution for your platform and download.

Move/rename the downloaded file into `$LocalDistDir` with `$TapVersion` appended.

Resultant file should be of the form: `tanzu-framework-$PlatformName-amd64-$TapVersion.{tar,zip}`

Samples:

|===
| Platform | Path

| Linux | `local/distfiles/tanzu-framework-linux-amd64-1.3.0.tar`
| OS X | `local/distfiles/tanzu-framework-darwin-amd64-1.3.0.tar`
| Windows |`local/distfiles/tanzu-framework-windows-amd64-1.3.0.zip`
|===

==== Tanzu Cluster Essentials

Go to the the TanzuNet downloads for https://network.tanzu.vmware.com/products/tanzu-cluster-essentials[Cluster Essentials for VMware Tanzu, window="_new"].

Select the release that matches `$TanzuClusterEssentialsVersion`.

Select the distribution for your platform and download.
If you're installing on Windows, select the `linux` distribution.

Move the downloaded file into `$LocalDistDir`.

Resultant file should be of the form: `tanzu-cluster-essentials-$PlatformName-amd64-$TanzuClusterEssentialsVersion.tgz`

|===
| Platform | Path

| Linux | `local/distfiles/tanzu-cluster-essentials-linux-amd64-1.2.0.tgz`
| OS X | `local/distfiles/tanzu-cluster-essentials-darwin-amd64-1.2.0.tgz`
| Windows | `local/distfiles/tanzu-cluster-essentials-linux-amd64-1.2.0.tgz`
|===

== Credentials

Credentials are defined in a configuration file that is ignored by Git: `etc/credentials.ps1`.

Copy `link:share/templates/credentials.ps1[]` to `etc/`.

----
PS> Copy-Item share/templates/credentials.ps1 etc/
----

Configure credentials for your Docker registry and TanzuNet.

.Sample
----
$RegistryHost = "harbor-repo.vmware.com"
$RegistryUser = "joe"
$RegistryPass = "joepass"
$RegistryRepo = "joes_tap"

$TanzuNetHost = "registry.tanzu.vmware.com"
$TanzuNetUser = "joe@company.com"
$TanzuNetPass = "joepassdeux"
----

== Minikube

=== Minikube Cluster

Running `minikube-start` creates a cluster if necessary and then starts it.

----
PS> bin/minikube-start.ps1
----

=== Minikube Tunnel

The tunnel is required for TAP installation and workload deployments.

The tunnel runs in the foreground, `CTRL-C` to kill.

----
PS> bin/minikube-tunnel.ps1
----

== TAP

=== TAP Profile

Generate a TAP Profile based on your settings.
You only need to do this once, or when you've changed settings.

----
PS> bin/tap-profile.ps1
----

Review the generated file `etc/tap-profile.yaml` before proceeding, regenerating as needed.

=== TAP Install

IMPORTANT: A network connection to corporate network must be open.

IMPORTANT: The Minikube tunnel must be running.

Install TAP into the current K8s context.

----
PS> bin/tap-install.ps1
----

The installation takes some time, 10-30 mins.

== TAP Workloads

=== Overview

Deployed apps will be assigned an HTTP route of the form: `http://NAME.default.local`

Where `NAME` is that specified in the command: `tanzu apps workload create NAME ...`


Add a matching entry to your local hosts resolving the route host to the loopback IF.

Host file locations:

|===
| Platform | Path

| OS X | `/etc/hosts`
| Linux | `/etc/hosts`
| Windows |  `C:\Windows\System32\drivers\etc\hosts`
|===

.Sample
----
127.0.0.1	NAME.default.local.
----

=== Sample TAP Workload

Deploy the Application Accelerator https://github.com/vmware-tanzu/application-accelerator-samples/tree/main/weatherforecast-steeltoe[Steeltoe sample, window="_new"].

.Deploy
----
PS> tanzu apps workload create weatherforecast --git-repo https://github.com/vmware-tanzu/application-accelerator-samples --sub-path weatherforecast-steeltoe --git-branch main --type web --label app.kubernetes.io/part-of=weatherforecast --label tanzu.app.live.view=true --label tanzu.app.live.view.application.name=weatherforecast --annotation autoscaling.knative.dev/minScale=1 --namespace default --yes
----

.Follow progress
----
PS> tanzu apps workload tail weatherforecast --timestamp
----

Wait for the status to transition to `Ready`.
This may take a while.
5-15 mins.

.Checking Status
----
PS> tanzu apps workload get weatherforecast
...
NAME              READY   URL
weatherforecast   Ready   http://weatherforecast.default.local
----

Add a host entry for `weatherforecast.default.local`.

----
127.0.0.1 weatherforecast.default.local.
----

Access the app.

----
PS> curl http://weatherforecast.default.local/
----

== Custom Configuration.

Configuration defaults are loaded by `link:etc/config.ps1[]`.

Defaults are defined in:

* `link:etc/config.ps1[]`
* `link:etc/tap.ps1[]`
* `link:etc/minikube.ps1[]`

To load configuration in a shell session, run: `. etc/config.ps1`

To override defaults, copy `link:share/templates/overrides.ps1[]` to `etc/`.

.Sample
----
$MiniKubeMemory = "6g"
----

== FAQ

Did you get a message about credentials.ps1? Refer to <<Credentials>> for what to do next.
