:toc:
:toclevels: 3
:toc-placement!:
:toc-title!:
:linkattrs:

= _Tanzu Thingies_ =

toc::[]

== Overview

This repo contains a collection of utilities to help with things Tanzu.

|===
| Util | Description

| `minikube-delete` | Deletes a Minikube cluster.
| `minikube-start` | Creates/starts a Minikube cluster.
| `minikube-stop` | Stops a Minikube cluster cluster.
| `minikube-tunnel` | Creates a Minikube cluster tunnel.
|===

Many of the example commands below work as-is on both Windows and non-Windows and can be copy-pasted as is.

.Sample Command
----
$ bin/sample-command
----

In situations where this is not the case, platform-specific commands are shown.

.Sample Platform Commands
----
# OSX
$ bin/osx-command

# Windows
$ bin\win-command.ps1
----

== Prereqs

=== `docker`

`docker` is provided by https://www.docker.com/products/docker-desktop/[Docker for Desktop, window="_new"].

=== `envsubst`

.envsubst
----
# OSX
$ homebrew install gettext

# Windows
> scoop install envsubst
----

=== `kubectl`

`kubectl` is provided by https://www.docker.com/products/docker-desktop/[Docker for Desktop, window="_new"].

=== `minikube`

----
# OSX
$ brew install minikube

# Windows
> scoop install minikube
----

=== `unzip`

`unzip` is only required for Windows.

----
# Windows
> scoop install unzip
----

== Configure

Configuration is set by loading the `config` for your platform.

The utilities in this repo load configuration when they are run.

You can load the configuration into your shell by sourcing `etc/config`.

NOTE: Shell examples in this doc assume a loaded configuration.

.Shell Configuration
----
$ . etc/config
----

=== Settings

The default settings should work out-of-the-box.

Default settings are defined in:

* `link:etc/config[]`
* `link:etc/tap[]`
* `link:etc/minikube[]`

To override defaults, copy `link:share/examples/overrides[]` to `etc/`.

.Overrides
----
# OSX/Linux
$ cp share/examples/overrides etc/

# Windows
$ copy share\examples\overrides.ps1 etc\
----

.Sample `etc/overrides`
----
MINIKUBE_MEMORY=6g
TAP_VERSION=1.2.2
----

=== Credentials

Credentials are defined in a specialized configuration that is ignored by Git.

Copy `link:share/examples/credentials[]` to `etc/`.

.Credentials
----
# OSX/Linux
$ cp share/examples/credentials etc/

# Windows
$ copy share\examples\credentials.ps1 etc\
----

Configure credentials for TanzuNet and a Docker registry.

.Sample `etc/credentials`
----
REGISTRY_HOST=harbor-repo.vmware.com
REGISTRY_USERNAME=joe
REGISTRY_PASSWORD=joepass
REGISTRY_REPO=joes_tap

TANZUNET_USERNAME=joe@company.com
TANZUNET_PASSWORD=joepassdeux
----


== TAP Tools

=== `tanzu`

Go to the the TanzuNet downloads for https://network.pivotal.io/products/tanzu-application-platform/[VMware Tanzu Application Platform, window="_new"].

Select the `tap-cli-tap` bundle for your platform and download.

Rename the downloaded file, appending `TAP_VERSION`.

.Example
----
# OSX
$ mkdir -p $DIST_DIR
$ mv ~/Downloads/tanzu-framework-darwin-amd64.tar ${DIST_DIR}/tanzu-framework-darwin-amd64-${TAP_VERSION}.tar

# Windows
$ mkdir $Env:DIST_DIR
$ move "$Env:UserProfile\Downloads\tanzu-framework-windows-amd64.zip" "$Env:DIST_DIR\tanzu-framework-windows-amd64-$Env:TAP_VERSION.zip"
----

== Cluster

=== Minikube Cluster

Running the `minikube-start` creates a cluster if necessary and then starts it.

----
$ bin/minikube-start
----

=== Minikube Tunnel

NOTE: The Minikube tunnel may require elevated permissions.

The tunnel is required for TAP installation.
If packages are failing to reconcile, it may be due to lack of a running tunnel.

The tunnel runs in the foreground, `CTRL-C` to kill.

----
$ bin/minikube-tunnel
----
