:toc:
:toclevels: 3
:toc-placement!:
:toc-title!:
:linkattrs:

= _Tanzu Thingies_ =

toc::[]

== Overview

This repo contains a collection of utilities to help with things Tanzu.

|===
| Util | Description

| `minikube-delete.ps1` | Deletes a Minikube cluster.
| `minikube-start.ps1` | Creates/starts a Minikube cluster.
| `minikube-stop.ps1` | Stops a Minikube cluster cluster.
| `minikube-tunnel.ps1` | Creates a Minikube cluster tunnel.
| `prereq-install.ps1` | Installs prerequisite tools.
| `tanzu-cli-install.ps1` | Installs Tanzu CLI and plugins.
| `tanzu-cluster-essentials-install.ps1` | Installs Tanzu Cluster Essentials.
| `tap-install.ps1` | Installs TAP into current K8s context.
| `tap-profile.ps1` | Creates a TAP profile.
| `tap-version.ps1` | Displays the version of TAP running in the current K8s context.
|===

== Prereqs

=== PowerShell

For Windows, install a recent version, >=7.2, from the the PowerShell https://github.com/PowerShell/PowerShell/releases[releases].
The PowerShell that ships with Windows is too old for these scripts.

For OS X, install using `brew install powershell`.

=== Docker for Desktop

https://www.docker.com/products/docker-desktop/

If using a WSL backend and Minikube is complaining about not enough resources, check out https://docs.microsoft.com/en-us/windows/wsl/wsl-config#wslconfig[instructions for increasing WSL resource allocation].

=== Tools

The prerequisite tools for your platform are defined in one of:

* `link:etc/prereqs-darwin.ps1[]`
* `link:etc/prereqs-windows.ps1[]`

You can install the tools manually, or by running:

----
PS> bin/prereq-install.ps1
----

Running the above script requires one of the below installers:

|===
| Installer | Platform | Home

| `brew` | OS X | https://brew.sh/
| `scoop` | Windows | https://scoop.sh/
|===

Did you get a message about credentials.ps1? Refer to <<Credentials>> for what to do next.

== Configure

Configuration is defined in `link:etc/config.ps1[]`.

The utilities in this repo load this configuration when they are run.

NOTE: Shell examples in this doc assume a loaded configuration.

.Shell Configuration
----
PS> . etc/config.ps1
----

=== Settings

The default settings should work out-of-the-box.

Default settings are defined in:

* `link:etc/config.ps1[]`
* `link:etc/tap.ps1[]`
* `link:etc/minikube.ps1[]`

To override defaults, copy `link:share/templates/overrides.ps1[]` to `etc/`.

.Overrides
----
PS> Copy-Item share/templates/overrides.ps1 etc/
----

.Sample `etc/overrides.ps1`
----
$MiniKubeMemory = "6g"
----

=== Credentials

Credentials are defined in a discrete configuration that is ignored by Git.

Copy `link:share/templates/credentials.ps1[]` to `etc/`.

.Credentials
----
PS> Copy-Item share/templates/credentials.ps1 etc/
----

Configure credentials for TanzuNet and a Docker registry.

.Sample `etc/credentials.ps1`
----
$RegistryHost = "harbor-repo.vmware.com"
$RegistryUser = "joe"
$RegistryPass = "joepass"
$RegistryRepo = "joes_tap"

$TanzuNetHost = "registry.tanzu.vmware.com"
$TanzuNetUser = "joe@company.com"
$TanzuNetPass = "joepassdeux"
----

== TAP Tools

The Tanzu CLI and Cluster Essentials are required. Below are a scripted approach (using the pivnet cli) and a manual approach.

=== Using pivnet cli

==== Install the pivnet cli
On OSX run `brew install pivotal/tap/pivnet-cli`

On other platforms, get the latest release for your platform at https://github.com/pivotal-cf/pivnet-cli/releases, ensure the file is executable and on the path. On Windows you'll want to rename the file to `pivnet.exe`

After the CLI is installed, https://network.pivotal.io/docs/api#how-to-authenticate[login, window="_new"]

==== Run the script

The included script assumes `pivnet` is available on the path and you are already logged in:

----
PS> bin/tanzu-fetch.ps1
----

=== Manual downloading files

==== Tanzu CLI

Go to the the TanzuNet downloads for https://network.tanzu.vmware.com/products/tanzu-application-platform/[VMware Tanzu Application Platform, window="_new"].

Select the release that matches `$TapVersion`.

Select the `tanzu-cli-tap` distribution for your platform.

Move/rename the downloaded file into `$LocalDistDir` with `$TapVersion` appended.

Resultant file will be of the form: `$LocalDistDir/tanzu-framework-$PlatformName-amd64-$TapVersion.$PlatformArchive`

Samples:

|===
| Platform | Path

| Linux | `local/distfiles/tanzu-framework-linux-amd64-1.3.0.tar`
| OS X | `local/distfiles/tanzu-framework-darwin-amd64-1.3.0.tar`
| Windows |`local/distfiles/tanzu-framework-windows-amd64-1.3.0.zip`
|===

==== Tanzu Cluster Essentials

Go to the the TanzuNet downloads for https://network.tanzu.vmware.com/products/tanzu-cluster-essentials[Cluster Essentials for VMware Tanzu, window="_new"].

Select the release that matches `$TanzuClusterEssentialsVersion`.

Select the distribution for your platform. If you're installing on Windows, select the `linux` distribution.

Move the downloaded file into `$LocalDistDir`.

Resultant file will be of the form: `$LocalDistDir/tanzu-cluster-essentials-$PlatformName-amd64-$TanzuClusterEssentialsVersion.tgz`

|===
| Platform | Path

| Linux | `local/distfiles/tanzu-cluster-essentials-linux-amd64-1.2.0.tgz`
| OS X | `local/distfiles/tanzu-cluster-essentials-darwin-amd64-1.2.0.tgz`
| Windows | `local/distfiles/tanzu-cluster-essentials-linux-amd64-1.2.0.tgz`
|===

== Cluster

=== Minikube Cluster

Running `minikube-start` creates a cluster if necessary and then starts it.

----
PS> bin/minikube-start.ps1
----

=== Minikube Tunnel

The tunnel is required for TAP installation.
If packages are failing to reconcile, it may be due to lack of a running tunnel.

The tunnel runs in the foreground, `CTRL-C` to kill.

----
PS> bin/minikube-tunnel.ps1
----

== TAP

=== Before You Begin

* link:#prereqs[Prereqs] are installed for your platform
* link:#tap-tools[TAP Tools] are downloaded into expected paths
* link:#credentials[Credentials] are configured
* link:#minikube-cluster[cluster is running]
* link:#minikube-tunnel[tunnel is running], if using MiniKube
* network connection to corporate network

=== TAP Profile

Generate a TAP Profile based on your settings.
You only need to do this once, or when you've changed settings.

----
PS> bin/tap-profile.ps1
----

This generates the file `etc/tap-profile.yaml`.
Probably a good idea to give it a once-over before proceeding.

=== TAP Install

Install TAP into the current K8s context.

----
PS> bin/tap-install.ps1
----

The installation takes some time.
10-30 mins.
YMMV.

To check on the installation process: `tanzu package installed list -A`

== Sample TAP Deployment

Deploy the sample Steeltoe app.

----
PS> tanzu apps workload create weatherforecast --git-repo https://github.com/vmware-tanzu/application-accelerator-samples --sub-path weatherforecast-steeltoe --git-branch main --type web --label app.kubernetes.io/part-of=weatherforecast --label tanzu.app.live.view=true --label tanzu.app.live.view.application.name=weatherforecast --annotation autoscaling.knative.dev/minScale=1 --namespace default --yes
----

Follow progress.

----
PS> tanzu apps workload tail weatherforecast --timestamp
----

Check if ready.
This may take a while.
5-15 mins.
YMMV.

----
PS> tanzu apps workload get weatherforecast
...
NAME              READY   URL
weatherforecast   Ready   http://weatherforecast.default.local
----

Add a host entry for `weatherforecast.default.local`.

----
127.0.0.1 weatherforecast.default.local.
----

Access the app.

----
PS> curl http://weatherforecast.default.local/
----
