:toc:
:toclevels: 2
:toc-placement!:
:toc-title!:
:linkattrs:

= _Tanzu Thingies_ =

toc::[]

== Prerequisites

=== PowerShell

For Windows, install a recent version, >=7.2, from the the PowerShell https://github.com/PowerShell/PowerShell/releases[releases].
The PowerShell that ships with Windows is too old for these scripts.

For OS X, install using: `brew install powershell`

=== 3rd Party Tools

The prerequisite 3rd party tools for your platform are defined in one of:

* `link:etc/prereqs-darwin.ps1[]`
* `link:etc/prereqs-windows.ps1[]`

You can install the tools manually, or by running:

----
PS> bin/prereq-install.ps1
----
Running the above script requires one of the below installers:

|===
| Installer | Platform | Home

| `brew` | OS X | https://brew.sh/
| `scoop` | Windows | https://scoop.sh/
|===

=== Pivnet CLI

Install `pivnet` from the https://github.com/pivotal-cf/pivnet-cli/[Pivnet CLI] project, either using a platform installer or downloading a release.

Ensure the file is executable and on your path. On Windows be sure to rename the file to `pivnet.exe`.

After the CLI is installed, https://network.pivotal.io/docs/api#how-to-authenticate[login, window="_new"] to the https://network.pivotal.io/[Tanzu Network, window="_new"].

== Configuration

Configuration defaults are loaded by sourcing `link:etc/config.ps1[]`.

=== Loading into a Shell

To load configuration in a shell session:

----
PS> . etc/config.ps1
----

=== Customizing

To override defaults, copy `link:share/templates/overrides.ps1[]` to `etc/`.

.Sample
----
$TapVersion = "1.6.0-build.39"
----

== FAQ

_This section intentionally left blank._
