:toc:
:toclevels: 3
:toc-placement!:
:toc-title!:
:linkattrs:

= _Tanzu Thingies_ =

toc::[]

== Overview

This repo contains a collection of utilities to help with things Tanzu.

|===
| Util | Description

| `essentials-install.ps1` | Installs VMware Cluster Essentials.
| `minikube-delete.ps1` | Deletes a Minikube cluster.
| `minikube-start.ps1` | Creates/starts a Minikube cluster.
| `minikube-stop.ps1` | Stops a Minikube cluster cluster.
| `minikube-tunnel.ps1` | Creates a Minikube cluster tunnel.
| `prereq-install.ps1` | Installs prerequisite tools.
| `tanzu-cli-install.ps1` | Installs Tanzu CLI and plugins.
| `tap-install.ps1` | Installs TAP into current K8s context.
| `tap-profile.ps1` | Creates a TAP profile.
| `tap-version.ps1` | Displays the version of TAP running in the current K8s context.
|===

== Prereqs

=== PowerShell

For Windows, install a recent version, >=7.2, from the the PowerShell https://github.com/PowerShell/PowerShell/releases[releases].
The PowerShell that ships with Windows is too old for these scripts.

For Darwin, install using `brew install powershell`.

=== Docker for Desktop

https://www.docker.com/products/docker-desktop/

If using a WSL backend and Minikube is complaining about not enough resources, check out https://docs.microsoft.com/en-us/windows/wsl/wsl-config#wslconfig[instructions for increasing WSL resource allocation].

=== Tools

The prerequisite tools for your platform are defined in one of:

* `link:etc/prereqs-darwin.ps1[]`

You can install the tools manuallay, or by running:

----
PS> bin/prereq-install.ps1
----

Running the above script requires one of the below installers:

|===
| Installer | Platform | Home

| `brew` | Darwin | https://brew.sh/
|===

== Configure

Configuration is defined in `link:etc/config.ps1[]`.

The utilities in this repo load this configuration when they are run.

NOTE: Shell examples in this doc assume a loaded configuration.

.Shell Configuration
----
PS> . etc/config.ps1
----

=== Settings

The default settings should work out-of-the-box.

Default settings are defined in:

* `link:etc/config.ps1[]`
* `link:etc/tap.ps1[]`
* `link:etc/minikube.ps1[]`

To override defaults, copy `link:share/examples/overrides.ps1[]` to `etc/`.

.Overrides
----
PS> Copy-Item share/examples/overrides.ps1 etc/
----

.Sample `etc/overrides.ps1`
----
Env:TAP_VERSION = "1.2.2"
Env:MINIKUBE_MEMORY = "6g"
----

=== Credentials

Credentials are defined in a discrete configuration that is ignored by Git.

Copy `link:share/examples/credentials.ps1[]` to `etc/`.

.Credentials
----
PS> Copy-Item share/examples/credentials.ps1 etc/
----

Configure credentials for TanzuNet and a Docker registry.

.Sample `etc/credentials`
----
$Env:REGISTRY_HOST = "harbor-repo.vmware.com"
$Env:REGISTRY_USER = "joe"
$Env:REGISTRY_PASS = "joepass"
$Env:REGISTRY_REPO = "joes_tap"

$Env:TANZUNET_USER = "joe@company.com"
$Env:TANZUNET_PASS = "joepassdeux"
----

== TAP Tools

=== Tanzu CLI

Go to the the TanzuNet downloads for https://network.tanzu.vmware.com/products/tanzu-application-platform/[VMware Tanzu Application Platform, window="_new"].

Select the release that matches `TAP_VERSION`.

Select the `tap-cli-tap` bundle for your platform and download.

Move/rename the downloaded file into `LOCAL_DIST_DIR` with `TAP_VERSION` appended.

.Example
----
PS> New-Item -Path $Env:LOCAL_DIST_DIR -ItemType Directory
PS> Move-Item ~/Downloads/tanzu-framework-$Env:PLATFORM-amd64.$Env:ARCHIVE "$Env:LOCAL_DIST_DIR/tanzu-framework-$Env:PLATFORM-amd64-$Env:TAP_VERSION.$Env:ARCHIVE"
PS> dir local/distfiles

    Directory: C:\Users\ccheetham\src\github.com\steeltoeoss-incubator\tanzu-thingies\local\distfiles

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---           9/14/2022  2:12 PM      206479649 tanzu-framework-windows-amd64-1.2.2.zip
----

== Cluster

=== Minikube Cluster

Running `minikube-start` creates a cluster if necessary and then starts it.

----
PS> bin/minikube-start.ps1
----

=== Minikube Tunnel

WARNING: The Minikube tunnel requires elevated permissions.

The tunnel is required for TAP installation.
If packages are failing to reconcile, it may be due to lack of a running tunnel.

The tunnel runs in the foreground, `CTRL-C` to kill.

----
PS> bin/minikube-tunnel.ps1
----

== TAP

=== Before You Begin

* link:#tap-tools[TAP product bundles] are downloaded into expected paths
* link:#minikube-cluster[cluster is running]
* link:#minikube-tunnel[tunnel is running]
* network connection to corporate network

=== TAP Profile

Generate a TAP Profile based on your settings.
You only need to do this once, or when you've changed settings.

----
PS> bin/tap-profile.ps1
----

This generates the file `etc/tap-profile.yaml`.
Probably a good idea to give it a once-over before proceeding.

=== TAP Install

Install TAP into the current K8s context.

----
PS> bin/tap-install.ps1
----

The installation takes some time.
10-30 mins.
YMMV.

=== Workload Notes

Deployed apps will be assigned an HTTP route of the form:

`http://NAME.default.local`

where `NAME` is that specified in the command:

`tanzu apps workload create NAME ...`.

Add a matching entry to your local hosts resolving the route host to the loopback IF.

Host file locations:

|===
| Platform | path

| Linux | `/etc/hosts`
| Darwin | `/etc/hosts`
| Windows |  `C:\Windows\System32\drivers\etc\hosts`
|===

.Sample
----
127.0.0.1	NAME.default.local.
----

== Sample TAP Deployment

Deploy the Spring sample Java app.

----
PS> tanzu apps workload create weatherforecast --git-repo https://github.com/vmware-tanzu/application-accelerator-samples --sub-path weatherforecast-steeltoe --git-branch main --type web --label app.kubernetes.io/part-of=weatherforecast --label tanzu.app.live.view=true --label tanzu.app.live.view.application.name=weatherforecast --annotation autoscaling.knative.dev/minScale=1 --namespace default --yes
----

Follow progress.

----
PS> tanzu apps workload tail weatherforecast --timestamp
----

Check if ready.
This may take a while.
5-15 mins.
YMMV.

----
PS> tanzu apps workload get weatherforecast
...
NAME              READY   URL
weatherforecast   Ready   http://weatherforecast.default.local
----

Add a host entry for `weatherforecast.default.local`.

----
127.0.0.1 weatherforecast.default.local.
----

Access the app.

----
PS> curl http://weatherforecast.default.local/
----
