:toc:
:toclevels: 3
:toc-placement!:
:toc-title!:
:linkattrs:

= _Tanzu Thingies_ =

toc::[]

== Overview

This repo contains a collection of utilities to help with things Tanzu.

|===
| Util | Description

| `minikube-create` | Creates a Minikube cluster.
| `minikube-delete` | Deletes a Minikube cluster.
| `minikube-tunnel` | Creates a Minikube cluster tunnel.
|===

== Configure

Configuration is set by loading the `config` for your platform.

The utilities in this repo load configuration when they are run.

You can load the configuration into your shell by sourcing `etc/config`.

NOTE: Shell examples in this doc assume a loaded configuration.

.Shell Configuration
----
# OSX/Linux
$ . etc/config
----

=== Settings

The default settings should work out-of-the-box.

Default settings are defined in:

* `link:etc/config[]`
* `link:etc/tap[]`
* `link:etc/minikube[]`

To override defaults, copy `link:share/examples/overrides[]` to `etc/`.

.Overrides
----
# OSX/Linux
$ cp share/examples/overrides etc/
----

.Sample etc/overrides
----
MINIKUBE_CPUS=4
TAP_VERSION=1.2.2
----

=== Credentials

Credentials are defined in a specialized configuration that is ignored by Git.

Copy `link:share/examples/credentials[]` to `etc/`.

.Credentials
----
# OSX/Linux
$ cp share/examples/credentials etc/
----

Configure credentials for TanzuNet and a Docker registry.

.Sample etc/credentials
----
REGISTRY_HOST=harbor-repo.vmware.com
REGISTRY_USERNAME=joe
REGISTRY_PASSWORD=joepassdeux
REGISTRY_REPO=joes_tap

TANZUNET_USERNAME=joe@company.com
TANZUNET_PASSWORD=joepass
----

== Tooling

=== System Tools

==== `envsubst`

`envsubst` is in included in `gettext` distributions.

.envsubst
----
# OSX
$ homebrew install gettext
----

==== `tar`

`tar` should be present on OSX and Linux.

=== Docker/Kubernetes

==== `docker/kubectl`

`docker` and `kubectl` are provided by https://www.docker.com/products/docker-desktop/[Docker for Desktop].

==== `minikube`

----
# OSX
$ brew install minikube
----

=== TAP Tools

==== `tanzu`

Go to the the TanzuNet downloads for https://network.pivotal.io/products/tanzu-application-platform/[VMware Tanzu Application Platform].

Select the `tap-cli-tap` bundle for your platform and download.

Rename the downloaded file, appending `TAP_VERSION`.

.Example
----
# OSX
$ mkdir -p $DIST_DIR
$ mv ~/Downloads/tanzu-framework-darwin-amd64.tar ${DIST_DIR}/tanzu-framework-darwin-amd64-${TAP_VERSION}.tar
----

== Cluster

=== Minikube Cluster

Running the `minikube-start` creates a cluster if necessary and then starts it.

.minikube-start
----
# OSX/Linux
$ bin/minikube-start
----

=== Minikube Tunnel

NOTE: The Minikube tunnel requires elevated permissions.

The tunnel is required for TAP installation.
If packages are failing to reconcile, it may be due to lack of running tunnel.

The tunnel runs in the foreground, `CTRL-C` to kill.

.minikube-tunnel
----
# OSX/Linux
$ bin/minikube-tunnel
----
