$LocalDir = "$BaseDir/local/$TapVersion"
$LocalConfigDir = "$LocalDir/etc"
$LocalCacheDir = "$LocalDir/var"
$LocalDataDir = "$LocalDir/share"
$LocalOptDir = "$LocalDir/opt"
$LocalDownloadDir = "$LocalCacheDir/downloads"
