# do not edit this file; override values in local.sh

PROG=`basename $0`
BASE_DIR=$(cd $(dirname $BASH_SOURCE)/.. && pwd)
CONFIG_DIR=$BASE_DIR/etc
LIB_DIR=$BASE_DIR/lib
DATA_DIR=$BASE_DIR/share
THINGY_DIR=$BASE_DIR/thingies
DISTFILE_DIR=${DISTFILE_DIR:=$BASE_DIR/distfiles}
LOCAL_DIR=${LOCAL_DIR:=$BASE_DIR/local}
WORK_DIR=${WORK_DIR:=$BASE_DIR/work}

KUBERNETES_VENDOR=${KUBERNETES_VENDOR:-detect}

source $LIB_DIR/functions.sh

case $OSTYPE in
  darwin*)
    OS=darwin
    ;;
  *)
    die "unsupported OS: $OSTYPE"
    ;;
esac
machine=$(uname -m)
case $machine in
  x86_64)
    ARCH=amd64
    ;;
  *)
    die "unsupported architecture: $machine"
    ;;
esac

PATH=$LOCAL_DIR/bin:$PATH

source $CONFIG_DIR/tanzu.sh
source $CONFIG_DIR/versions.sh
[ -f $CONFIG_DIR/credentials.sh ] && source $CONFIG_DIR/credentials.sh
[ -f $CONFIG_DIR/local.sh ] && source $CONFIG_DIR/local.sh

TANZUNET_USERNAME=$(echo $TANZUNET_CREDENTIALS | cut -d: -f1)
TANZUNET_PASSWORD=$(echo $TANZUNET_CREDENTIALS | cut -d: -f2)
DOCKER_USERNAME=$(echo $DOCKER_CREDENTIALS | cut -d: -f1)
DOCKER_PASSWORD=$(echo $DOCKER_CREDENTIALS | cut -d: -f2)
