# do not edit this file; override values in local.sh

PROG=`basename $0`
BASE_DIR=$(cd $(dirname $BASH_SOURCE)/.. && pwd)
CONFIG_DIR=$BASE_DIR/etc
LIB_DIR=$BASE_DIR/lib
DATA_DIR=$BASE_DIR/share
CACHE_DIR=$BASE_DIR/var
THINGY_DIR=$DATA_DIR/thingies
DISTFILE_DIR=${DISTFILE_DIR:=$CACHE_DIR/distfiles}
CATALOG_DIR=$CACHE_DIR/catalog
WORK_DIR=$CACHE_DIR/work
LOCAL_DIR=$BASE_DIR/local

KUBERNETES_VENDOR=${KUBERNETES_VENDOR:-detect}

source $LIB_DIR/functions.sh

case $OSTYPE in
  darwin*)
    OS=darwin
    ;;
  *)
    die "unsupported OS: $OSTYPE"
    ;;
esac
machine=$(uname -m)
case $machine in
  x86_64)
    ARCH=amd64
    ;;
  *)
    die "unsupported architecture: $machine"
    ;;
esac

PATH=$LOCAL_DIR/bin:$PATH

for f in $CONFIG_DIR/profile.d/*; do
  source $f
done
[ -f $CONFIG_DIR/credentials.sh ] && source $CONFIG_DIR/credentials.sh
[ -f $CONFIG_DIR/local.sh ] && source $CONFIG_DIR/local.sh

TANZUNET_USERNAME=$(echo $TANZUNET_CREDENTIALS | cut -d: -f1)
TANZUNET_PASSWORD=$(echo $TANZUNET_CREDENTIALS | cut -d: -f2)
DOCKER_USERNAME=$(echo $DOCKER_CREDENTIALS | cut -d: -f1)
DOCKER_PASSWORD=$(echo $DOCKER_CREDENTIALS | cut -d: -f2)
