# do not edit this file; override values in local.sh

TANZUNET_HOSTNAME=registry.tanzu.vmware.com
CLUSTER_ESSENTIALS_BUNDLE=registry.tanzu.vmware.com/tanzu-cluster-essentials/cluster-essentials-bundle@sha256:82dfaf70656b54dcba0d4def85ccae1578ff27054e7533d08320244af7fb0343
TAP_CATALOG=
TAP_DOMAIN_NAME=tap.steeltoe.io
TAP_GUI_URL=http://34.134.58.240:7000
TAP_ACCELERATORS="\
  https://github.com/sample-accelerators/tanzu-java-web-app \
  https://github.com/sample-accelerators/csharp-weatherforecast \
  https://github.com/sample-accelerators/fsharp-weatherforecast \
  https://github.com/sample-accelerators/steeltoe-weatherforecast"
