# do not edit this file

TAP_VERSION=${TAP_VERSION:-1.0.2}
TANZU_CLUSTER_ESSENTIALS_VERSION=${TANZU_CLUSTER_ESSENTIALS_VERSION:-1.0.0}
TANZU_CLI_TAP_VERSION=${TANZU_CLI_TAP_VERSION:-0.11.1}
TANZUNET_HOSTNAME=registry.tanzu.vmware.com
CLUSTER_ESSENTIALS_BUNDLE=registry.tanzu.vmware.com/tanzu-cluster-essentials/cluster-essentials-bundle@sha256:82dfaf70656b54dcba0d4def85ccae1578ff27054e7533d08320244af7fb0343
TAP_INSTALL_NAMESPACE=tap-install
TAP_CATALOG=
TAP_DOMAIN_NAME=tap.steeltoe.io
TAP_GUI_URL=http://tap-gui.${TAP_DOMAIN_NAME}
TAP_ACCELERATORS="\
  https://github.com/sample-accelerators/tanzu-java-web-app \
  https://github.com/sample-accelerators/csharp-weatherforecast \
  https://github.com/sample-accelerators/fsharp-weatherforecast \
  https://github.com/sample-accelerators/steeltoe-weatherforecast \
  "
TANZU_CLUSTER_ESSENTIALS_HOME=~/tanzu-cluster-essentials
TANZU_CLI_HOME=~/tanzu
